Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,19 +35,16 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
         run: mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
-      - name: Build with Maven
-        run: mvn -B package --file pom.xml
-        working-directory: ${{ github.workspace }}
-      - name: Set JAR file location as an environment variable
-        run: echo "JAR_FILE_PATH=$(ls -d Maven/target/*.jar)" >> $GITHUB_ENV
-      - name: Display JAR file location
-        run: echo "JAR file is located at:$JAR_FILE_PATH"
-      - name: Show Contents of target Directory
-        run: ls -R /target
-      - name: Debug Docker Context
+      - name: Check for jar file
         run: |
-          pwd
-          ls -R          
+          if [ -n "$(find target -maxdepth 1 -name '*.jar' -print -quit)" ]; then
+            echo "jAR file found."
+          else
+            echo "jAR file not found."
+            exit 1
+          fi
+      - name: Show Contents of /target Directory
+        run: ls -R $GITHUB_WORKSPACE/target
   deploy:
     needs: build
     runs-on: ubuntu-latest
